# imports packages

import geopandas as gpd
import osmnx as ox
import pybdshadow
import pandas as pd
import numpy as np
import transbigdata as tbd
import networkx as nx

from suncalc import get_times
from shapely.geometry import MultiPolygon, Point

from pybdshadow import bdshadow_sunlight
from pybdshadow.preprocess import bd_preprocess
from pybdshadow.analysis import get_timetable, cal_sunshine, cal_sunshadows, cal_shadowcoverage, count_overlapping_features

from sunshade import list_of_selected_days, import_OSM, data_preprocessing, solar_radiation_requests



def sun_shade_solar_panel(lat=40.775, lng=-73.96, dist=50, precision = 10800, accuracy=1, padding=1800): #Attention distance!
    '''
    Calculate the sunshine time in given date for a position, taking into account buildings arount a circle of dist in meter

    Parameters
    --------------------
    lat : float
        latitude
    lng : float
        longitude  
    dist : int
        distance around the define point of interest in meter, limit the surround buildings used in the analysis  
    precision : number
        time precision(s)
    accuracy : number
        size of grids. Produce vector polygons if set as `vector` 
    padding : number
        padding time before and after sunrise and sunset

    Return
    ----------
    grids : GeoDataFrame
        grids generated by TransBigData in study area, each grids have a `time` column store the sunshine time

    '''
    # import data from NASA
    df_solar_radiation_year = solar_radiation_requests(lat, lng)
    
    # import data from OSM
    raw_buildings = import_OSM(lat=40.775, lng=-73.96, lat_lag = 0.8)
    
    # Data preprocessing
    buildings = data_preprocessing(raw_buildings)
        
    # Loop on the list of the day
    day_list = list_of_selected_days(start = '2021-01-03', end = '2021-12-26', n=2)
    
    # results dataframe preparation
    selected_days=pd.DataFrame()
    selected_days['date'] = day_list
    selected_days['roof']=0
    selected_days['sunshadow']=0 # init col sunshine   
    
    # Test if selected position is on a roof
    p=Point(lng, lat)
    building_test = buildings['geometry'].apply(lambda x: x.intersects(p))
    if building_test.any()==True: 
        roof = True
    else:
        roof = False
    
    # Calculate sunshine time on the building roof or on the ground regarding the roof parameter
    # => substraction of the time mesured in shadow to the daylight time (sunset - sunrise) 
    for i in range(len(selected_days)):
        day=str(day_list[i])
        day[:10]
        sunshine = pybdshadow.cal_sunshine(buildings,
                                    day=day,
                                    roof=roof,
                                    accuracy=accuracy,
                                    precision=precision)
        # intersection point with polygon : point p = lng/lat chosen, polygon = area of calculated time of sunshine
        sunshine['intersect'] = sunshine['geometry'].apply(lambda x: x.intersects(p))
        df_test = sunshine[sunshine['intersect'] == True]
        # append the dataframe : 
        selected_days['roof'][i]=roof
        selected_days['sunshadow'][i]=(np.mean(df_test['Hour'])) 
        
    # Merge info from API and Cal_sunshine 
    selected_days # TO DO search data in API and merge it
        
    return selected_days
