# imports packages

import geopandas as gpd
import osmnx as ox
import pybdshadow
import pandas as pd
import numpy as np
import transbigdata as tbd
import networkx as nx

from suncalc import get_times
from shapely.geometry import MultiPolygon, Point

from pybdshadow import bdshadow_sunlight
from pybdshadow.preprocess import bd_preprocess
from pybdshadow.analysis import get_timetable, cal_sunshine, cal_sunshadows, cal_shadowcoverage, count_overlapping_features

from sunshade import list_of_selected_days, import_OSM, data_preprocessing
from sunshade.solar_radiation_requests import historical_solar_radiation


def sun_shade_solar_panel(lat=40.775, lng=-73.96, dist=50, precision = 10800, accuracy=1, padding=1800, start = '2021-01-03', end = '2021-12-26', n=2): #Attention distance!
    '''
    Calculate the sunshine time in given date for a position, taking into account buildings arount a circle of dist in meter

    Parameters
    --------------------
    lat : float
        latitude
    lng : float
        longitude  
    dist : int
        distance around the define point of interest in meter, limit the surround buildings used in the analysis  
    precision : number
        time precision(s)
    accuracy : number
        size of grids. Produce vector polygons if set as `vector` 
    padding : number
        padding time before and after sunrise and sunset
    start = date like '2021-01-03'
        first day of the time range
    end = date like '2021-12-03'
        last day of the time range
    n = int 2,minimum
        number of days
          
    Return
    ----------
    selected_days : pandas DataFrame
        sunshine regarding shadows and solar raidation regarding weather per day for the POI
    sunshine_all_date : Geopandas DataFrame
        grids generated by TransBigData in study area, each grids have a `time` column store the sunshine time
        

    '''
    # import data from NASA
    df_solar_radiation_year = historical_solar_radiation(lat, lng)
    
    # import data from OSM
    raw_buildings = import_OSM.import_OSM(lat=lat, lng=lng, dist=dist, lat_lag = 0.8)
    
    # Data preprocessing
    buildings = data_preprocessing.data_preprocessing(raw_buildings)
        
    # Loop on the list of the day
    day_list = list_of_selected_days.list_of_selected_days(start = start, end = end, n=n)
    
    # results dataframe preparation
    selected_days=pd.DataFrame()
    selected_days['latitude'] = lat
    selected_days['longitude'] = lng
    selected_days['date'] = day_list
    selected_days['roof']=0
    selected_days['sunshadow']=0 # init col sunshine
    selected_days['daylight_hour']=0
    sunshine_all_date = pd.DataFrame()
    
    # Test if selected position is on a roof
    p=Point(lng, lat)
    building_test = buildings['geometry'].apply(lambda x: x.intersects(p))
    if building_test.any()==True: 
        roof = True
    else:
        roof = False
    
    # Calculate sunshine time on the building roof or on the ground regarding the roof parameter
    # => substraction of the time mesured in shadow to the daylight time (sunset - sunrise) 
    for i in range(len(selected_days)):
        day=str(day_list[i])
        day = day[:10]
        sunshine = pybdshadow.cal_sunshine(buildings,
                                    day=day,
                                    roof=roof,
                                    accuracy=accuracy,
                                    precision=precision)
        # intersection point with polygon : point p = lng/lat chosen, polygon = area of calculated time of sunshine
        sunshine['intersect'] = sunshine['geometry'].apply(lambda x: x.intersects(p))
        df_test = sunshine[sunshine['intersect'] == True]
        
        # append the dataframe :
        
        times = get_times(date, lon, lat)
        date_sunrise = times['sunrise']
        data_sunset = times['sunset']
        timestamp_sunrise = pd.Series(date_sunrise).astype('int')
        timestamp_sunset = pd.Series(data_sunset).astype('int')
        selected_days.daylight_hour.iloc[i]=(timestamp_sunset.iloc[i]-timestamp_sunrise.iloc[i])/(1000000000*3600)
        
        selected_days.roof.iloc[i]=roof 
        selected_days.sunshadow.iloc[i]=(np.mean(df_test['Hour']))
        # save the data for one day
        file_name_1=f"Data_{lat}_{lng}_{day}"
        sunshine.to_csv(f'{file_name_1}.csv')
        
        # append the sunshine_all :
        sunshine['latitude'] = lat
        sunshine['longitude'] = lng
        sunshine['date'] = day
        # save the geodataframe for one day
        file_name_2=f"Geodata_{lat}_{lng}_{day}"
        sunshine.to_csv(f'{file_name_2}.csv')
        
        #Merge the dataframes
        sunshine_all_date = pd.concat([sunshine_all_date,sunshine])
        print(day)
        
        
    # Merge info from API and Cal_sunshine 
    selected_days = selected_days.merge(df_solar_radiation_year, how='inner', on='date')
    
    
    return selected_days, sunshine_all_date

if __name__ == '__main__':
    print('The function is running with the default parameters')
    #sun_shade_solar_panel(lat=40.775, lng=-73.96, dist=50, precision = 10800, accuracy=1, padding=1800, start = '2021-01-03', end = '2021-12-26', n=2)
